server:
  port: 80
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dentist?serverTimezone=GMT%2B8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false
pagehelper:
  helper-dialect: mysql
  reasonable: true
  supportMethodsArguments: true
  pageSizeZero: true
  params: count=countSql