server:
  port: 80
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dentist
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    cache: false
mybatis:
  #配置映射文件的扫描
  mapper-locations: classpath:com/example/demo/dao/*.xml
  #配置别名的扫描
  type-aliases-package: com.example.demo.entity
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  pageSizeZero: true
  params: count=countSql